from flask import render_template, redirect, request
from app import app
from models.books import book_list, add_new_book, remove_book
from models.book import Book

@app.route('/')
def home():
   return render_template('home.html')

@app.route('/books')
def index():
    return render_template('index.html', book_list=book_list)


#when this request is made it saves whats inside <> as a variable index
#when that happens the single_book function is triggered which takes index as its argument
#it then uses index which is an int corrosponding to the list position of a Book 
#the index number is generated by the html a tag which forwards to url with the relevent index list number
@app.route('/books/<index>')
def single_book(index):
  #the index can then be used to get the book in question and saves it to a variable chosen book
  chosen_book = book_list[int(index)]
  
  #now the book.html template is rendered and the chosen book is passed into the placeholders on the page
  return render_template('book.html', book=chosen_book)


@app.route('/books', methods=['POST'])
def add_book():
   bookTitle = request.form['title']
   bookAuthor = request.form['author']
   bookGenre = request.form['genre']
   newBook = Book(title=bookTitle, author=bookAuthor, genre=bookGenre)
   add_new_book(newBook)

   return render_template('index.html', book_list=book_list)

@app.route("/books/delete/<index>", methods=["POST"])
def books_delete(index):
    remove_book(int(index))
    return redirect("/books")